// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yvyettbeuxskpplaabgn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl2eWV0dGJldXhza3BwbGFhYmduIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkxMzQ4OTQsImV4cCI6MjA3NDcxMDg5NH0.RcXpCyIxa3mxL_e31jtlqvgSTk-kKi3s1p-xd_Hz7EI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});